# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list

clock: vector# logical or vector

# The logger's name must be logger
configuration :
  - name : alice
    ip : 128.237.180.48
    port : 12344
  - name : bob
    ip : 128.237.180.48
    port : 14255
  - name : charlie
    ip : 128.237.180.48
    port : 12998
  - name : daphnie
    ip : 128.237.214.183
    port : 1987
  - name : eason
    ip : 128.237.214.183
    port : 1988
  - name : flora
    ip : 128.237.214.183
    port : 1989
  - name : gaga
    ip : 128.237.214.183
    port : 1990
  #- name : logger
  #  ip : 127.0.0.1
  #  port : 1989
groups:
  - name: Group1
    members:
      - alice
      - bob
      - charlie




  - name: alice
    members:
      - alice
      - bob
      - charlie
  - name: bob
    members:
      - bob
      - daphnie
      - flora
  - name: charlie
    members:
      - charlie
      - eason
      - flora
  - name: daphnie
    members:
      - alice
      - daphnie
      - eason
  - name: eason
    members:
      - bob
      - eason
      - gaga
  - name: flora
    members:
      - alice
      - flora
      - gaga
  - name: gaga
    members:
      - charlie
      - daphnie
      - gaga
sendRules :
#  - action: delay
#    kind: delay

receiveRules :
#  - action: delay
#    dest: bob

