# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list

clock: vector# logical or vector

# The logger's name must be logger
configuration :
  - name : alice
    ip : 127.0.0.1
    port : 12344 # This is the incoming port on which MP will listen
                 # May be changed for further communication as usual
  - name : bob
    ip : 127.0.0.1
    port : 14255
  - name : charlie
    ip : 127.0.0.1
    port : 12998
  - name : daphnie
    ip : 127.0.0.1
    port : 1987
  - name : logger
    ip : 127.0.0.1
    port : 1989

groups:
  - name: Group1
    members:
      - alice
      - bob
      - charlie
  - name: Group2
    members:
      - daphnie
      - bob
      - charlie

sendRules : 
  - action: drop
    src: charlie
    dest: bob
    kind: drop


receiveRules :
 