# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list

clock: vector # logical or vector

# The logger's name must be logger
configuration :
  - name : alice
    ip : 128.237.185.125
    port : 12344 # This is the incoming port on which MP will listen
                 # May be changed for further communication as usual
  - name : bob
    ip : 128.237.185.125
    port : 14255
  - name : charlie
    ip : 128.237.220.174
    port : 12998
  - name : daphnie
    ip : 128.237.185.125
    port : 1987
  - name : logger
    ip : 128.237.220.174
    port : 1989

sendRules :



receiveRules :
 